/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AddJNI */

#ifndef _Included_AddJNI
#define _Included_AddJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AddJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AddJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AddJNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AddJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AddJNI
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AddJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AddJNI
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_AddJNI_div
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
